### ISSUE TITLE
exiting the TUI always outputs an error: "UI exit unexpectedly Error: UI exited unexpectedly."

### ISSUE THREAD

**Issue by ecshreve** [amonks/run#95]
Any time I press "q" to exit the TUI i see these errors printed out

```
UI exit unexpectedly
Error: UI exited unexpectedly.
```

The task looks like this:
```toml
[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = """
    echo "Running development mode..."
    while true; do sleep 1; done
  """
```

---

<img width="618" alt="Screenshot 2024-03-30 at 10 49 44 AM" src="https://github.com/amonks/run/assets/1425775/8a132866-d0e7-455d-883b-fb93a6fffa64">
